// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReminderServiceClient is the client API for ReminderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReminderServiceClient interface {
	AddRemainder(ctx context.Context, in *AddRemainderRequest, opts ...grpc.CallOption) (*AddRemainderResponse, error)
	DeleteRemainder(ctx context.Context, in *DeleteRemainderRequest, opts ...grpc.CallOption) (*DeleteRemainderResponse, error)
	ListRemainders(ctx context.Context, in *ListRemaindersRequest, opts ...grpc.CallOption) (*ListRemaindersResponse, error)
	UpdateRemainder(ctx context.Context, in *UpdateRemainderRequest, opts ...grpc.CallOption) (*UpdateRemainderResponse, error)
}

type reminderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReminderServiceClient(cc grpc.ClientConnInterface) ReminderServiceClient {
	return &reminderServiceClient{cc}
}

func (c *reminderServiceClient) AddRemainder(ctx context.Context, in *AddRemainderRequest, opts ...grpc.CallOption) (*AddRemainderResponse, error) {
	out := new(AddRemainderResponse)
	err := c.cc.Invoke(ctx, "/remainderprotos.ReminderService/AddRemainder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) DeleteRemainder(ctx context.Context, in *DeleteRemainderRequest, opts ...grpc.CallOption) (*DeleteRemainderResponse, error) {
	out := new(DeleteRemainderResponse)
	err := c.cc.Invoke(ctx, "/remainderprotos.ReminderService/DeleteRemainder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) ListRemainders(ctx context.Context, in *ListRemaindersRequest, opts ...grpc.CallOption) (*ListRemaindersResponse, error) {
	out := new(ListRemaindersResponse)
	err := c.cc.Invoke(ctx, "/remainderprotos.ReminderService/ListRemainders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) UpdateRemainder(ctx context.Context, in *UpdateRemainderRequest, opts ...grpc.CallOption) (*UpdateRemainderResponse, error) {
	out := new(UpdateRemainderResponse)
	err := c.cc.Invoke(ctx, "/remainderprotos.ReminderService/UpdateRemainder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReminderServiceServer is the server API for ReminderService service.
// All implementations must embed UnimplementedReminderServiceServer
// for forward compatibility
type ReminderServiceServer interface {
	AddRemainder(context.Context, *AddRemainderRequest) (*AddRemainderResponse, error)
	DeleteRemainder(context.Context, *DeleteRemainderRequest) (*DeleteRemainderResponse, error)
	ListRemainders(context.Context, *ListRemaindersRequest) (*ListRemaindersResponse, error)
	UpdateRemainder(context.Context, *UpdateRemainderRequest) (*UpdateRemainderResponse, error)
	mustEmbedUnimplementedReminderServiceServer()
}

// UnimplementedReminderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReminderServiceServer struct {
}

func (UnimplementedReminderServiceServer) AddRemainder(context.Context, *AddRemainderRequest) (*AddRemainderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRemainder not implemented")
}
func (UnimplementedReminderServiceServer) DeleteRemainder(context.Context, *DeleteRemainderRequest) (*DeleteRemainderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRemainder not implemented")
}
func (UnimplementedReminderServiceServer) ListRemainders(context.Context, *ListRemaindersRequest) (*ListRemaindersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRemainders not implemented")
}
func (UnimplementedReminderServiceServer) UpdateRemainder(context.Context, *UpdateRemainderRequest) (*UpdateRemainderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRemainder not implemented")
}
func (UnimplementedReminderServiceServer) mustEmbedUnimplementedReminderServiceServer() {}

// UnsafeReminderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReminderServiceServer will
// result in compilation errors.
type UnsafeReminderServiceServer interface {
	mustEmbedUnimplementedReminderServiceServer()
}

func RegisterReminderServiceServer(s grpc.ServiceRegistrar, srv ReminderServiceServer) {
	s.RegisterService(&ReminderService_ServiceDesc, srv)
}

func _ReminderService_AddRemainder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRemainderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).AddRemainder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remainderprotos.ReminderService/AddRemainder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).AddRemainder(ctx, req.(*AddRemainderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_DeleteRemainder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRemainderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).DeleteRemainder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remainderprotos.ReminderService/DeleteRemainder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).DeleteRemainder(ctx, req.(*DeleteRemainderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_ListRemainders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRemaindersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).ListRemainders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remainderprotos.ReminderService/ListRemainders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).ListRemainders(ctx, req.(*ListRemaindersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_UpdateRemainder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRemainderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).UpdateRemainder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remainderprotos.ReminderService/UpdateRemainder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).UpdateRemainder(ctx, req.(*UpdateRemainderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReminderService_ServiceDesc is the grpc.ServiceDesc for ReminderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReminderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remainderprotos.ReminderService",
	HandlerType: (*ReminderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRemainder",
			Handler:    _ReminderService_AddRemainder_Handler,
		},
		{
			MethodName: "DeleteRemainder",
			Handler:    _ReminderService_DeleteRemainder_Handler,
		},
		{
			MethodName: "ListRemainders",
			Handler:    _ReminderService_ListRemainders_Handler,
		},
		{
			MethodName: "UpdateRemainder",
			Handler:    _ReminderService_UpdateRemainder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remainder.proto",
}
