apiVersion: apps/v1
kind: Deployment
metadata:
  name: addservice
spec:
  selector:
    matchLabels:
      app: addservice
  template:
    metadata:
      labels:
        app: addservice
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: gcr.io/architect-demos/addservice:v4.0
          ports:
          - containerPort: 50054
          env:
          - name: PROJECT_ID
            value: "architect-demos"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: addservice
spec:
  type: ClusterIP
  selector:
    app: addservice
  ports:
  - name: grpc
    port: 50054
    targetPort: 50054
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendservice
spec:
  selector:
    matchLabels:
      app: backendservice
  template:
    metadata:
      labels:
        app: backendservice
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: gcr.io/architect-demos/backendservice:v4.0
          ports:
          - containerPort: 50052
          env:
          - name: PROJECT_ID
            value: "architect-demos"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backendservice
spec:
  type: ClusterIP
  selector:
    app: backendservice
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: gcr.io/architect-demos/frontend:v4.0
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: BACKEND_SERVICE_ADDR
            value: "backendservice:50052"
          - name: UPDATE_SERVICE_ADDR
            value: "updateservice:50053"
          - name: ADD_SERVICE_ADDR
            value: "addservice:50054"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: updateservice
spec:
  selector:
    matchLabels:
      app: updateservice
  template:
    metadata:
      labels:
        app: updateservice
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: gcr.io/architect-demos/updateservice:v4.0
          ports:
          - containerPort: 50053
          env:
          - name: PROJECT_ID
            value: "architect-demos"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: updateservice
spec:
  type: ClusterIP
  selector:
    app: updateservice
  ports:
  - name: grpc
    port: 50053
    targetPort: 50053
