// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: remainder.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Remainder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemainderId   string                 `protobuf:"bytes,1,opt,name=remainderId,proto3" json:"remainderId,omitempty"`
	Remainder     string                 `protobuf:"bytes,2,opt,name=remainder,proto3" json:"remainder,omitempty"`
	UserUID       string                 `protobuf:"bytes,3,opt,name=userUID,proto3" json:"userUID,omitempty"`
	RemainderTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=remainderTime,proto3" json:"remainderTime,omitempty"`
}

func (x *Remainder) Reset() {
	*x = Remainder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Remainder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remainder) ProtoMessage() {}

func (x *Remainder) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remainder.ProtoReflect.Descriptor instead.
func (*Remainder) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{0}
}

func (x *Remainder) GetRemainderId() string {
	if x != nil {
		return x.RemainderId
	}
	return ""
}

func (x *Remainder) GetRemainder() string {
	if x != nil {
		return x.Remainder
	}
	return ""
}

func (x *Remainder) GetUserUID() string {
	if x != nil {
		return x.UserUID
	}
	return ""
}

func (x *Remainder) GetRemainderTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RemainderTime
	}
	return nil
}

type AddRemainderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remainder *Remainder `protobuf:"bytes,1,opt,name=remainder,proto3" json:"remainder,omitempty"`
}

func (x *AddRemainderRequest) Reset() {
	*x = AddRemainderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRemainderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemainderRequest) ProtoMessage() {}

func (x *AddRemainderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemainderRequest.ProtoReflect.Descriptor instead.
func (*AddRemainderRequest) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{1}
}

func (x *AddRemainderRequest) GetRemainder() *Remainder {
	if x != nil {
		return x.Remainder
	}
	return nil
}

type AddRemainderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remainder *Remainder `protobuf:"bytes,1,opt,name=remainder,proto3" json:"remainder,omitempty"`
}

func (x *AddRemainderResponse) Reset() {
	*x = AddRemainderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRemainderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemainderResponse) ProtoMessage() {}

func (x *AddRemainderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemainderResponse.ProtoReflect.Descriptor instead.
func (*AddRemainderResponse) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{2}
}

func (x *AddRemainderResponse) GetRemainder() *Remainder {
	if x != nil {
		return x.Remainder
	}
	return nil
}

type DeleteRemainderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemainderID string `protobuf:"bytes,1,opt,name=remainderID,proto3" json:"remainderID,omitempty"`
}

func (x *DeleteRemainderRequest) Reset() {
	*x = DeleteRemainderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRemainderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRemainderRequest) ProtoMessage() {}

func (x *DeleteRemainderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRemainderRequest.ProtoReflect.Descriptor instead.
func (*DeleteRemainderRequest) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRemainderRequest) GetRemainderID() string {
	if x != nil {
		return x.RemainderID
	}
	return ""
}

type DeleteRemainderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemainderID *Remainder `protobuf:"bytes,1,opt,name=remainderID,proto3" json:"remainderID,omitempty"`
}

func (x *DeleteRemainderResponse) Reset() {
	*x = DeleteRemainderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRemainderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRemainderResponse) ProtoMessage() {}

func (x *DeleteRemainderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRemainderResponse.ProtoReflect.Descriptor instead.
func (*DeleteRemainderResponse) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRemainderResponse) GetRemainderID() *Remainder {
	if x != nil {
		return x.RemainderID
	}
	return nil
}

type ListRemaindersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUID string `protobuf:"bytes,1,opt,name=userUID,proto3" json:"userUID,omitempty"`
}

func (x *ListRemaindersRequest) Reset() {
	*x = ListRemaindersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRemaindersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemaindersRequest) ProtoMessage() {}

func (x *ListRemaindersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemaindersRequest.ProtoReflect.Descriptor instead.
func (*ListRemaindersRequest) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{5}
}

func (x *ListRemaindersRequest) GetUserUID() string {
	if x != nil {
		return x.UserUID
	}
	return ""
}

type ListRemaindersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remainders []*Remainder `protobuf:"bytes,1,rep,name=remainders,proto3" json:"remainders,omitempty"`
}

func (x *ListRemaindersResponse) Reset() {
	*x = ListRemaindersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRemaindersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemaindersResponse) ProtoMessage() {}

func (x *ListRemaindersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemaindersResponse.ProtoReflect.Descriptor instead.
func (*ListRemaindersResponse) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{6}
}

func (x *ListRemaindersResponse) GetRemainders() []*Remainder {
	if x != nil {
		return x.Remainders
	}
	return nil
}

type UpdateRemainderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remainder *Remainder `protobuf:"bytes,1,opt,name=remainder,proto3" json:"remainder,omitempty"`
}

func (x *UpdateRemainderRequest) Reset() {
	*x = UpdateRemainderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRemainderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemainderRequest) ProtoMessage() {}

func (x *UpdateRemainderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemainderRequest.ProtoReflect.Descriptor instead.
func (*UpdateRemainderRequest) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRemainderRequest) GetRemainder() *Remainder {
	if x != nil {
		return x.Remainder
	}
	return nil
}

type UpdateRemainderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remainder *Remainder `protobuf:"bytes,2,opt,name=remainder,proto3" json:"remainder,omitempty"`
}

func (x *UpdateRemainderResponse) Reset() {
	*x = UpdateRemainderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remainder_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRemainderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemainderResponse) ProtoMessage() {}

func (x *UpdateRemainderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remainder_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemainderResponse.ProtoReflect.Descriptor instead.
func (*UpdateRemainderResponse) Descriptor() ([]byte, []int) {
	return file_remainder_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRemainderResponse) GetRemainder() *Remainder {
	if x != nil {
		return x.Remainder
	}
	return nil
}

var File_remainder_proto protoreflect.FileDescriptor

var file_remainder_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x55, 0x49, 0x44, 0x12, 0x40, 0x0a, 0x0d, 0x72,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x4f, 0x0a,
	0x13, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x50,
	0x0a, 0x14, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x22, 0x3a, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x57, 0x0a, 0x17,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x31, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x55, 0x49, 0x44, 0x22, 0x54, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x22, 0x52,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x22, 0x53, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x32, 0x9d, 0x03, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0c, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x27, 0x2e, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61,
	0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x26, 0x2e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x64, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x27, 0x2e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x72, 0x65, 0x6d, 0x69, 0x61,
	0x6e, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_remainder_proto_rawDescOnce sync.Once
	file_remainder_proto_rawDescData = file_remainder_proto_rawDesc
)

func file_remainder_proto_rawDescGZIP() []byte {
	file_remainder_proto_rawDescOnce.Do(func() {
		file_remainder_proto_rawDescData = protoimpl.X.CompressGZIP(file_remainder_proto_rawDescData)
	})
	return file_remainder_proto_rawDescData
}

var file_remainder_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_remainder_proto_goTypes = []interface{}{
	(*Remainder)(nil),               // 0: remainderprotos.Remainder
	(*AddRemainderRequest)(nil),     // 1: remainderprotos.AddRemainderRequest
	(*AddRemainderResponse)(nil),    // 2: remainderprotos.AddRemainderResponse
	(*DeleteRemainderRequest)(nil),  // 3: remainderprotos.DeleteRemainderRequest
	(*DeleteRemainderResponse)(nil), // 4: remainderprotos.DeleteRemainderResponse
	(*ListRemaindersRequest)(nil),   // 5: remainderprotos.ListRemaindersRequest
	(*ListRemaindersResponse)(nil),  // 6: remainderprotos.ListRemaindersResponse
	(*UpdateRemainderRequest)(nil),  // 7: remainderprotos.UpdateRemainderRequest
	(*UpdateRemainderResponse)(nil), // 8: remainderprotos.UpdateRemainderResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_remainder_proto_depIdxs = []int32{
	9,  // 0: remainderprotos.Remainder.remainderTime:type_name -> google.protobuf.Timestamp
	0,  // 1: remainderprotos.AddRemainderRequest.remainder:type_name -> remainderprotos.Remainder
	0,  // 2: remainderprotos.AddRemainderResponse.remainder:type_name -> remainderprotos.Remainder
	0,  // 3: remainderprotos.DeleteRemainderResponse.remainderID:type_name -> remainderprotos.Remainder
	0,  // 4: remainderprotos.ListRemaindersResponse.remainders:type_name -> remainderprotos.Remainder
	0,  // 5: remainderprotos.UpdateRemainderRequest.remainder:type_name -> remainderprotos.Remainder
	0,  // 6: remainderprotos.UpdateRemainderResponse.remainder:type_name -> remainderprotos.Remainder
	1,  // 7: remainderprotos.ReminderService.AddRemainder:input_type -> remainderprotos.AddRemainderRequest
	3,  // 8: remainderprotos.ReminderService.DeleteRemainder:input_type -> remainderprotos.DeleteRemainderRequest
	5,  // 9: remainderprotos.ReminderService.ListRemainders:input_type -> remainderprotos.ListRemaindersRequest
	7,  // 10: remainderprotos.ReminderService.UpdateRemainder:input_type -> remainderprotos.UpdateRemainderRequest
	2,  // 11: remainderprotos.ReminderService.AddRemainder:output_type -> remainderprotos.AddRemainderResponse
	4,  // 12: remainderprotos.ReminderService.DeleteRemainder:output_type -> remainderprotos.DeleteRemainderResponse
	6,  // 13: remainderprotos.ReminderService.ListRemainders:output_type -> remainderprotos.ListRemaindersResponse
	8,  // 14: remainderprotos.ReminderService.UpdateRemainder:output_type -> remainderprotos.UpdateRemainderResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_remainder_proto_init() }
func file_remainder_proto_init() {
	if File_remainder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_remainder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Remainder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remainder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRemainderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remainder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRemainderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remainder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRemainderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remainder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRemainderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remainder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRemaindersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remainder_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRemaindersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remainder_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRemainderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remainder_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRemainderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_remainder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remainder_proto_goTypes,
		DependencyIndexes: file_remainder_proto_depIdxs,
		MessageInfos:      file_remainder_proto_msgTypes,
	}.Build()
	File_remainder_proto = out.File
	file_remainder_proto_rawDesc = nil
	file_remainder_proto_goTypes = nil
	file_remainder_proto_depIdxs = nil
}
